---
version: '3'
services:
  freqtrade-BreakEven:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-BreakEven
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8082:8082"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy BreakEven
  freqtrade-Diamond:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-Diamond
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8081:8081"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy Diamond
  freqtrade-GodStra:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-GodStra
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8083:8083"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy GodStra
  freqtrade-Heracles:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-Heracles
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8084:8084"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy Heracles
  freqtrade-HourBasedStrategy:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-HourBasedStrategy
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8086:8086"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy HourBasedStrategy
  freqtrade-InformativeSample:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-InformativeSample
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8085:8085"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy InformativeSample
  freqtrade-HourBasedStrategy:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-HourBasedStrategy
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8087:8087"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy HourBasedStrategy
  freqtrade-MultiMa:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-MultiMa
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8088:8088"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy MultiMa
  freqtrade-Supertrend:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-Supertrend
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8089:8089"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy Supertrend
  freqtrade-Swing-High-To-Sky:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-Swing-High-To-Sky
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8090:8090"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy Swing-High-To-Sky